org.gradle.jvmargs=-Xmx4G
kotlin.incremental=false

mod_id=boilerplate
mod_group=net.kernelpanicsoft.boilerplate
mod_version=0.1.0-SNAPSHOT
mod_display_name=Boilerplate
mod_description=A steampunky pneumatic-tube logistics and storage mod.
mod_authors=Kernel Panic
mod_credits=
mod_url=https://github.com/kernel-panic-codecave/TubularStorage
mod_source=https://github.com/kernel-panic-codecave/TubularStorage
mod_license=GPL-3.0-or-later
